# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np
import random

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [12]:
# mat1 = np.array(np.random.randint(0,9,9)).reshape(3,3)
# mat2 = np.array(np.random.randint(9,18,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", np.array(mat1+mat2))
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*(mat1)-2*(mat2))


print("\nAddition of a scalar (100)\n-------------------------\n", mat1+1000)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", pow(mat1,3))
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[0 0 7]
 [0 5 0]
 [8 1 1]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[13  9 12]
 [15 16 17]
 [14 12  9]]

Addition
------------------
 [[13  9 19]
 [15 21 17]
 [22 13 10]]

Multiplication
------------------
 [[  0   0  84]
 [  0  80   0]
 [112  12   9]]

Division
------------------
 [[0.         0.         0.58333333]
 [0.         0.3125     0.        ]
 [0.57142857 0.08333333 0.11111111]]

Linear combination: 3*A - 2*B
-----------------------------
 [[-26 -18  -3]
 [-30 -17 -34]
 [ -4 -21 -15]]

Addition of a scalar (100)
-------------------------
 [[1000 1000 1007]
 [1000 1005 1000]
 [1008 1001 1001]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  0   0 343]
 [  0 125   0]
 [512   1   1]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[0.         0.         2.64575131]
 [0.  

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [25]:
from numpy.random import randint as ri
mat1 = np.array(np.random.randint(0,9,9)).reshape(3,3)
mat2 = np.array(np.random.randint(0,5,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis =0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis =1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis =1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis =0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = np.array(np.random.randint(1,99,9)).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[7 3 2]
 [5 7 5]
 [1 6 4]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[1 4 1]
 [3 4 4]
 [3 4 0]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 40

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [13 16 11]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [12 17 11]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 42 175  24]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [ 9 64  0]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 4.444444444444445

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2.00

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [29]:
##Solution
mat2 = np.array(np.random.randint(0,9,9)).reshape(3,3)

print("Before changing shape\n",'-'*50,"\n",mat2)

mat3 =mat2.reshape(9,1)

print("After changing shape\n",'-'*50,"\n",mat3)


Before changing shape
 -------------------------------------------------- 
 [[1 3 3]
 [0 7 2]
 [5 6 1]]
After changing shape
 -------------------------------------------------- 
 [[1]
 [3]
 [3]
 [0]
 [7]
 [2]
 [5]
 [6]
 [1]]


### 4.Sort

In [30]:
A = np.array(np.random.randint(0,9,9)) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [5 7 8 5 6 8 1 3 7]

Here is the sorted vector
 -------------------------------------------------- 
 [1 3 5 5 6 7 7 8 8]


In [31]:
M = np.array(np.random.randint(0,9,25)).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis =1)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis =0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[4 5 3 5 1]
 [4 0 4 6 6]
 [6 5 8 1 5]
 [3 0 3 7 8]
 [3 3 8 2 0]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[1 3 4 5 5]
 [0 4 4 6 6]
 [1 5 5 6 8]
 [0 3 3 7 8]
 [0 2 3 3 8]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[3 0 3 1 0]
 [3 0 3 2 1]
 [4 3 4 5 5]
 [4 5 8 6 6]
 [6 5 8 7 8]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [32]:
# Fill the following ***** with appropriate solution.
a=np.array(np.random.randint(0,6,10))
b=np.array(np.random.randint(0,6,10))
c=np.array(np.random.randint(0,6,10))

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", max(a))
print("Max of b:",max(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))






a: [2 4 4 3 2 1 0 1 1 4]
b: [3 4 4 1 4 1 5 3 1 2]
c: [4 4 0 2 0 2 2 1 3 1]
Max of a: 4
Max of b: 5
Max of a location: 1
Max of b location: 6
Max of c location: 0


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [37]:

mat1 = np.array(np.random.randint(0,6,9)).reshape(3,3)
mat2 = np.array(np.random.randint(0,6,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", pow(mat1,2))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat1,2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[2 4 1]
 [5 5 1]
 [1 3 3]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[2 0 4]
 [0 1 1]
 [1 2 2]]

Sq-root of 1st matrix using np
------------------
 [[1.41421356 2.         1.        ]
 [2.23606798 2.23606798 1.        ]
 [1.         1.73205081 1.73205081]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[ 4 16  1]
 [25 25  1]
 [ 1  9  9]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.30103    0.60205999 0.        ]
 [0.69897    0.69897    0.        ]
 [0.         0.47712125 0.47712125]]

Modulo reminder using np
 -------------------------------------------------- 
 [[0 0 1]
 [1 1 1]
 [1 1 1]]


### 7.Generating matrices from distributions

In [40]:

print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(2,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
# print(********) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.array(np.random.randint(1,7,20))) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.97006785 0.82618051 0.72117685]
 [0.14298304 0.73603684 0.36935943]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.29649269 -1.42566188 -0.68131803]
 [-1.21105282  0.28860065  0.27832436]]
Random integer vector: [11 65 60 61 62 76 69 22 54 18]

Random integer matrix

20 samples drawn from a dice throw: [4 5 5 6 5 4 3 6 4 1 3 6 5 4 4 6 3 5 1 6]


### 8.Find the nearest value from a given number in an array using NumPy.

In [80]:
#Steps
#Create an array of 5 random element from 1 to 12

mat1 = np.array(np.random.randint(1,12,5))
print("The random array is \n",'-'*50,"\n",mat1)
mat_min =np.abs(mat1 -10)
mat_drop =np.where(mat_min ==0)
ls =[]

print("Mat after dropping  is \n",'-'*50,'\n',mat_drop)
mat_new =np.delete(mat_min,mat_drop)



# # Suppose find the nearest values of 10 in an array so set value=10
for i in mat_min:
    if (i == np.argmin(mat_new) ):
        ls.append(i)
        
        
print(ls)
mat1[ls] =10

print("Array after modification\n",'-'*50,'\n' ,mat1)

# print(np.argmin(np.where(mat1 -10)))

#find the index where difference is minimum and get the element

The random array is 
 -------------------------------------------------- 
 [1 8 9 5 8]
Mat after dropping  is 
 -------------------------------------------------- 
 (array([], dtype=int64),)
[2, 2]
Array after modification
 -------------------------------------------------- 
 [ 1  8 10  5  8]


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [ ]:
NA